### ISSUE TITLE
./gradlew clean build fails on Amazon Linux

### ISSUE THREAD

**Issue by cblack** [Netflix/suro#29]
Steps:
### Bring up a new Amazon Linux instance

``` bash
sudo yum -y update
sudo sum -y install git

git clone https://github.com/Netflix/suro.git
cd suro
./gradlew build
```
#### :suro-server

``` java
com.netflix.suro.server.TestSuroControl > testOnlyExitCommandWorks FAILED
    java.net.ConnectException at TestSuroControl.java:67
```

This error is intermittent.  Retrying the builds sometimes succeeds.  This may be because of the findAvailablePort method is returning a used port.

The source line is:

``` java
Socket client = new Socket("127.0.0.1", port);
```
#### :suro-client

``` java
com.netflix.suro.connection.TestConnectionOutPool > testOutPool FAILED
    java.lang.AssertionError at TestConnectionOutPool.java:67
```

Source:

``` java
final ConnectionPool pool = injector.getInstance(ConnectionPool.class);
assertEquals(pool.getPoolSize(), 1);
```

**Comment by noeliaoses** [comment]
Hi,
I'm trying to install Suro on a VirtualBox VM created with Vagrant. The build fails with the following errors (copied below).

The code I used on the fresh Ubuntu 14.04.4 LTS VM box is:

Step 1:  Install the latest git and gradle packages

sudo apt-get update
sudo apt-get install git gradle -y 

Step 2: install java

sudo apt-get install software-properties-common -yq  
sudo add-apt-repository ppa:webupd8team/java -y
sudo apt-get update

automatically accept licence when installing:

echo debconf shared/accepted-oracle-license-v1-1 select true | sudo debconf-set-selections
echo debconf shared/accepted-oracle-license-v1-1 seen true | sudo debconf-set-selections
sudo apt-get -y install oracle-java7-installer 

Step 3: install suro

git clone https://github.com/Netflix/suro.git
cd suro
./gradlew clean build

THE ERROR MESSAGES:

com.netflix.suro.connection.TestConnectionOutPool > testOutPool FAILED
    java.lang.AssertionError: expected:<0> but was:<1>
        at org.junit.Assert.fail(Assert.java:88)
        at org.junit.Assert.failNotEquals(Assert.java:743)
        at org.junit.Assert.assertEquals(Assert.java:118)
        at org.junit.Assert.assertEquals(Assert.java:555)
        at org.junit.Assert.assertEquals(Assert.java:542)
        at com.netflix.suro.connection.TestConnectionOutPool.setup(TestConnectionOutPool.java:104)
        at com.netflix.suro.connection.TestConnectionOutPool.testOutPool(TestConnectionOutPool.java:53)

com.netflix.suro.connection.TestConnectionPool > shouldBePopulatedWithNumberOfServersOnLessSenderThreads FAILED
    junit.framework.AssertionFailedError
        at junit.framework.Assert.fail(Assert.java:55)
        at junit.framework.Assert.assertTrue(Assert.java:22)
        at junit.framework.Assert.assertTrue(Assert.java:31)
        at com.netflix.suro.connection.TestConnectionPool.shouldBePopulatedWithNumberOfServersOnLessSenderThreads(TestConnectionPool.java:302)

com.netflix.suro.connection.TestConnectionPool > shouldBePopulatedWithNumberOfServersOnMoreSenderThreads FAILED
    junit.framework.AssertionFailedError: expected:<2> but was:<3>
        at junit.framework.Assert.fail(Assert.java:57)
        at junit.framework.Assert.failNotEquals(Assert.java:329)
        at junit.framework.Assert.assertEquals(Assert.java:78)
        at junit.framework.Assert.assertEquals(Assert.java:234)
        at junit.framework.Assert.assertEquals(Assert.java:241)
        at com.netflix.suro.connection.TestConnectionPool.shouldBePopulatedWithNumberOfServersOnMoreSenderThreads(TestConnectionPool.java:325)

43 tests completed, 3 failed
:suro-client:test FAILED

FAILURE: Build failed with an exception.
- What went wrong:
  Execution failed for task ':suro-client:test'.
  
  > There were failing tests. See the report at: file:///home/vagrant/suro/suro-client/build/reports/tests/index.html
- Exception is:
  org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':suro-client:test'.
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
  at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
  at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
  at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
  at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
  at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
  at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
  at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
  at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
  at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
  at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
  at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
  at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
  at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
  at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
  at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
  at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
  at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
  at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
  at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
  at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
  at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
  at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
  at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
  at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
  at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
  at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
  at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
  at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
  at org.gradle.launcher.Main.doAction(Main.java:33)
  at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
  at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
  at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
  at org.gradle.wrapper.BootstrapMainStarter.start(BootstrapMainStarter.java:30)
  at org.gradle.wrapper.WrapperExecutor.execute(WrapperExecutor.java:127)
  at org.gradle.wrapper.GradleWrapperMain.main(GradleWrapperMain.java:56)
  Caused by: org.gradle.api.GradleException: There were failing tests. See the report at: file:///home/vagrant/suro/suro-client/build/reports/tests/index.html
  at org.gradle.api.tasks.testing.Test.handleTestFailures(Test.java:1111)
  at org.gradle.api.tasks.testing.Test.executeTests(Test.java:542)
  at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
  at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
  at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
  at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
  ... 47 more

Thank you for your help!
Noelia
